spring.application.name=SecureWatch

spring.datasource.url=jdbc:postgresql://localhost:5432/SecureWatch
spring.datasource.username=postgres
spring.datasource.password=2285

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=YourVerySecretKeyThatIsAtLeast32CharactersLongToWorkWithHS256!
jwt.duration=3600000